services:
  vectordb-milvus-etcd:
    image: quay.io/coreos/etcd:v3.5.21
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - vectordb-milvus-etcd-data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    restart: on-failure
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  vectordb-milvus-minio:
    image: minio/minio:RELEASE.2025-04-08T15-41-24Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    # ports:
    #   - 19001:9001
    #   - 19000:9000
    volumes:
      - vectordb-milvus-minio-data:/minio_data
    command: minio server /minio_data --console-address ":9001"
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  vectordb-milvus-standalone:
    image: milvusdb/milvus:v2.5.9
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: vectordb-milvus-etcd:2379
      MINIO_ADDRESS: vectordb-milvus-minio:9000
    volumes:
      - vectordb-milvus-standalone-data:/var/lib/milvus
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - 19530:19530
      # - 19091:9091
    depends_on:
      - vectordb-milvus-etcd
      - vectordb-milvus-minio
  
  vectordb-milvus-attu:
    image: zilliz/attu:v2.5
    environment:
      MILVUS_URL: vectordb-milvus-standalone:19530
    ports:
      - 19540:3000
    restart: on-failure
    depends_on:
      - vectordb-milvus-standalone

volumes:
  vectordb-milvus-minio-data:
  vectordb-milvus-etcd-data:
  vectordb-milvus-standalone-data:
